name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to quantum@skushagra. Your issue has been noted and will be adressed soon'
        pr-message: 'Welcome to quantum@skushagra. You request will be processed soon.'
